### ISSUE TITLE
where is the data file?

### ISSUE THREAD

**Issue by jdfrost** [PacktPublishing/Machine-Learning-with-scikit-learn-Quick-Start-Guide#1]
Can't play with this code without the CSV file. The sample code is almost useless without the data that it requires to run.

**Comment by ManikandanKurup-Packt** [comment]
Hi @jdfrost 
The dataset has to be downloaded from Kaggle as mentioned in Chapter 2. Here is the link to the same:
[https://www.kaggle.com/ntnu-testimon/paysim1](https://www.kaggle.com/ntnu-testimon/paysim1)
